function Non_inv_opamp(type, V, f, R1, R2, Vps_plus, Vps_minus, N)

%the window
Fig=figure('Name','The Plots', ...
           'Units', 'normalized', ...
           'NumberTitle', 'off', ...
           'Position', [0.02 0.1 0.96 0.8], ...
           'Color', [0.65 0.5 1]);

%Text: Title_of_the_page: PLOTS
Title_of_the_page = uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.2 0.85 0.6 0.11],... 
'backgroundcolor',[0.65 0.5 1],...
'foregroundcolor','w',...
'Fontweight', 'bold',...
'FontSize',24,...
'FontName', 'Arial',...
'String','THE PLOTS');

%the input voltage
T=1/f;
t=(0:T/100:N*T);
w=2.*pi.*f;

uicontrol('style','PopupMenu',...
    'units','normalized',...
    'position',[0.72 0.2 0.1 0.1],...
    'value',type,...
    'string','Sinusoidal SIgnal|Triangular Signal',...
    'callback','type=get(gco,''value'');close;Non_inv_opamp(type, V, f, R1, R2, Vps_plus, Vps_minus, N);');

switch(type)
    case 1
Vin=V*sin(2*pi*f*t);
    case 2
Vin=(2*V/pi)*asin(sin(w.*t));
end;

%the output voltage
Vout=(1+(R2/R1))*Vin; %vout=gain*vin
for i = 1:length(t)
    if Vout(i)>=Vps_plus
        Vout(i)=Vps_plus;
    end;
end;
for i = 1:length(t)
    if Vout(i)<=Vps_minus
        Vout(i)=Vps_minus;
    end;
end;

%'foregroundcolor',[0.9 0.5 1],...

%the input voltage plot
The_input_voltage_plot = uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.18 0.85 0.13 0.05],... 
'backgroundcolor',[0.65 0.5 1],...
'foregroundcolor','w',...
'Fontweight', 'bold',...
'FontSize',12,...
'FontName', 'Arial',...
'String','THE INPUT VOLTAGE');

subplot('position',[0.1 0.65 0.3 0.2]);
plot(t,Vin,":k", 'LineWidth',4);%plot for vin
grid on;
legend('Vin');
xlabel('time [s]');
ylabel('Amplitude [V]');


%the output voltage plot
The_output_voltage_plot = uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.18 0.55 0.13 0.05],... 
'backgroundcolor',[0.65 0.5 1],...
'foregroundcolor','w',...
'Fontweight', 'bold',...
'FontSize',12,...
'FontName', 'Arial',...
'String','THE OUTPUT VOLTAGE');

subplot('position',[0.1 0.35 0.3 0.2]);
plot(t,Vout,"--b*");%plot for vout
grid on;
legend('Vout');
xlabel('time [s]');
ylabel('Amplitude [V]'); 

%Voltage Transfer Characteristic (VTC)
The_VTC_plot = uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.18 0.25 0.13 0.05],... 
'backgroundcolor',[0.65 0.5 1],...
'foregroundcolor','w',...
'Fontweight', 'bold',...
'FontSize',12,...
'FontName', 'Arial',...
'String','VOLTAGE TRANSFER CHARACTERISTIC (VTC)');

subplot('position',[0.1 0.05 0.3 0.2]);%plot for VTC
plot(Vin,Vout, 'Color',[0.9 0.01 1],'LineWidth', 3);
grid on;
xlabel('Vin');
ylabel('Vout');

% pushbutton CLOSE
Button_for_closing = uicontrol('Style','pushbutton',... 
'Units','normalized',... 
'Position',[0.9 0.9 0.08 .05],...
'String','CLOSE',...
'backgroundcolor','w',...
'foregroundcolor','k',...
'Fontweight', 'bold',...
'FontSize',12,...
'FontName', 'Arial',...
'Callback','close'); 

% TextButton Amplitude Voltage 
uicontrol('Style','text',... 
 'Units','normalized',...
 'Position',[0.5 0.63 0.1 0.1],...
 'backgroundcolor','w',...
 'foregroundcolor','k',...
 'Fontweight','bold',...
 'FontSize',12,...
 'FontName', 'Arial',...
 'string','Amplitude [V]');

% Edit for Amplitude Voltage
uicontrol('Style','edit',... 
 'Units','normalized',...
 'Position',[0.5 0.58 0.1 0.1],...
 'backgroundcolor',[0.9 0.8 0.9],...
 'foregroundcolor','k',...
 'Fontweight','bold',...
 'FontSize',12,...
 'FontName', 'Arial',...
 'String',V,... 
'Callback',['V=str2num(get(gco,''string'')),close;Non_inv_opamp(type, V, f, R1, R2, Vps_plus, Vps_minus, N);']);

% TextButton Frequency 
uicontrol('Style','text',... 
 'Units','normalized',...
 'Position',[0.61 0.63 0.1 0.1],...
 'backgroundcolor','w',...
 'foregroundcolor','k',...
 'Fontweight','bold',...
 'FontSize',12,...
 'FontName', 'Arial',...
 'string','Frequency [Hz]');

% Edit for Frequency
uicontrol('Style','edit',... 
 'Units','normalized',...
 'Position',[0.61 0.58 0.1 0.1],...
 'backgroundcolor',[0.9 0.8 0.9],...
 'foregroundcolor','k',...
 'Fontweight','bold',...
 'FontSize',12,...
 'FontName', 'Arial',...
 'String',f,... 
'Callback',['f=str2num(get(gco,''string'')),close;Non_inv_opamp(type, V, f, R1, R2, Vps_plus, Vps_minus, N);']);

% TextButton Resistance R1 
uicontrol('Style','text',... 
 'Units','normalized',...
 'Position',[0.72 0.63 0.1 0.1],...
 'backgroundcolor','w',...
 'foregroundcolor','k',...
 'Fontweight','bold',...
 'FontSize',12,...
 'FontName', 'Arial',...
 'string','Resistance R1 [Ohm]');

% Edit for Resistance R1
uicontrol('Style','edit',... 
 'Units','normalized',...
 'Position',[0.72 0.58 0.1 0.1],...
 'backgroundcolor',[0.9 0.8 0.9],...
 'foregroundcolor','k',...
 'Fontweight','bold',...
 'FontSize',12,...
 'FontName', 'Arial',...
 'String',R1,... 
'Callback',['R1=str2num(get(gco,''string'')),close;Non_inv_opamp(type, V, f, R1, R2, Vps_plus, Vps_minus, N);']);

% TextButton Resistance R2 
uicontrol('Style','text',... 
 'Units','normalized',...
 'Position',[0.72 0.45 0.1 0.1],...
 'backgroundcolor','w',...
 'foregroundcolor','k',...
 'Fontweight','bold',...
 'FontSize',12,...
 'FontName', 'Arial',...
 'string','Resistance R2 [Ohm]');

% Edit for Resistance R2
uicontrol('Style','edit',... 
 'Units','normalized',...
 'Position',[0.72 0.4 0.1 0.1],...
 'backgroundcolor',[0.9 0.8 0.9],...
 'foregroundcolor','k',...
 'Fontweight','bold',...
 'FontSize',12,...
 'FontName', 'Arial',...
 'String',R2,... 
'Callback',['R2=str2num(get(gco,''string'')),close;Non_inv_opamp(type, V, f, R1, R2, Vps_plus, Vps_minus, N);']);

% TextButton Vps- 
uicontrol('Style','text',... 
 'Units','normalized',...
 'Position',[0.61 0.45 0.1 0.1],...
 'backgroundcolor','w',...
 'foregroundcolor','k',...
 'Fontweight','bold',...
 'FontSize',12,...
 'FontName', 'Arial',...
 'string','Vps- [V]');

% Edit for Vps-
uicontrol('Style','edit',... 
 'Units','normalized',...
 'Position',[0.61 0.4 0.1 0.1],...
 'backgroundcolor',[0.9 0.8 0.9],...
 'foregroundcolor','k',...
 'Fontweight','bold',...
 'FontSize',12,...
 'FontName', 'Arial',...
 'String',Vps_minus,... 
'Callback',['Vps_minus=str2num(get(gco,''string'')),close;Non_inv_opamp(type, V, f, R1, R2, Vps_plus, Vps_minus, N);']);


% TextButton Vps+ 
uicontrol('Style','text',... 
 'Units','normalized',...
 'Position',[0.5 0.45 0.1 0.1],...
 'backgroundcolor','w',...
 'foregroundcolor','k',...
 'Fontweight','bold',...
 'FontSize',12,...
 'FontName', 'Arial',...
 'string','Vps+ [V]');

%edit for Vps+
uicontrol('Style','edit',... 
 'Units','normalized',...
 'Position',[0.5 0.4 0.1 0.1],...
 'backgroundcolor',[0.9 0.8 0.9],...
 'foregroundcolor','k',...
 'Fontweight','bold',...
 'FontSize',12,...
 'FontName', 'Arial',...
 'String',Vps_plus,... 
'Callback',['Vps_plus=str2num(get(gco,''string'')),close;Non_inv_opamp(type, V, f, R1, R2, Vps_plus, Vps_minus, N);']);

% TextButton Number of Periods 
uicontrol('Style','text',... 
 'Units','normalized',...
 'Position',[0.72 0.81 0.1 0.1],...
 'backgroundcolor','w',...
 'foregroundcolor','k',...
 'Fontweight','bold',...
 'FontSize',12,...
 'FontName', 'Arial',...
 'string','Number of periods');

% Edit for Number of periods
uicontrol('Style','edit',... 
 'Units','normalized',...
 'Position',[0.72 0.76 0.1 0.1],...
 'backgroundcolor',[0.9 0.8 0.9],...
 'foregroundcolor','k',...
 'Fontweight','bold',...
 'FontSize',12,...
 'FontName', 'Arial',...
 'String',N,... 
'Callback',['N=str2num(get(gco,''string'')),close;Non_inv_opamp(type, V, f, R1, R2, Vps_plus, Vps_minus, N);']);

% pushbutton SCHEMATIC
Button_for_sch = uicontrol('Style','pushbutton',... 
'Units','normalized',... 
'Position',[0.5 0.2 0.1 0.1],...
'String','SCHEMATIC',...
'backgroundcolor',[0.9 0.8 0.9],...
'foregroundcolor','k',...
'Fontweight', 'bold',...
'FontSize',12,...
'FontName', 'Arial',...
'Callback','schematic');

% pushbutton FORMULAS
Button_for_formulas = uicontrol('Style','pushbutton',... 
'Units','normalized',... 
'Position',[0.61 0.2 0.1 0.1],...
'String','FORMULAS',...
'backgroundcolor',[0.9 0.8 0.9],...
'foregroundcolor','k',...
'Fontweight', 'bold',...
'FontSize',12,...
'FontName', 'Arial',...
'Callback','formulas');

% pushbutton BACK
Button_for_closing = uicontrol('Style','pushbutton',... 
'Units','normalized',... 
'Position',[0.9 0.7 0.08 .05],...
'String','BACK',...
'backgroundcolor','w',...
'foregroundcolor','k',...
'Fontweight', 'bold',...
'FontSize',12,...
'FontName', 'Arial',...
'Callback','first_page'); 

%reset
uicontrol('Style','text',... 
 'Units','normalized',...
 'Position',[0.9 0.4 0.08 0.15],...
 'backgroundcolor','w',...
 'foregroundcolor','k',...
 'Fontweight','bold',...
 'FontSize',12,...
 'FontName', 'Arial',...
 'string','For RESET, click somewhere in the purple page');

%menu
b1 = uimenu('Label','Back','Callback','first_page');
cl = uimenu('Label','Close','Callback','close',...
 'Separator','on','Accelerator','Q');









